config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  get '/' => 'home#index'
  get '/about' => 'home#about'
  get '/song' => 'home#song'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :phone_number, :memo)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        
    end
    def about
        
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :phone_number %><br>
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :memo %><br>
    <%= f.text_area(:memo, size: "50x10") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>
<hr>

<table>
  <thead>
    <tr>
      <th>Name |</th>
      <th>Phone number |</th>
      <th>Memo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.phone_number %></td>
        <td><%= contact.memo %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Phone number:</strong>
  <%= @contact.phone_number %>
</p>

<p>
  <strong>Memo</strong>
  <%= @contact.memo %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/about.html.erb
<body>
    <h1>about</h1><br>
    <h5>about페이지입니다.</h2><br>
    <h5>제가 먼저 노래한번 불러보겠습니다.</h5><br>
    <h5>오빠 차 뽑았다 널 데리러 가<br>
    Baby Let's ride Hey<br>
    빨리 나와 Skkkkkrt<br>
    어서 타 달리자 어디든 괜찮아<br>
    Baby Let's ride<br>
    Let's do it All night<br>
    질리도록 말했잖아<br>
    돈 벌어서 데리러간다고<br>
    넌 그냥 몸만 오면 돼<br>
    쥐뿔 하나 없어도<br>
    날 믿어주던 사람들에게<br>
    확실히 보답해<br>
    Brake 없이 Accelerator<br>
    말년휴가처럼 달려가 제대로<br>
    신발대신 이젠 바퀴<br>
    멈출 생각 없어<br>
    아우토반이 된 앞길<br>
    풀릴 일 없게 <br>
    꽉 조여 매 안전벨트<br>
    걱정 마 너 말곤<br>
    아무도 안태워 내 옆엔<br>
    아까워 우리 나이가<br>
    좀 빨라도 겁내지마<br>
    가끔 속도위반 일탈<br>
    오빠 차 뽑았다 널 데리러 가<br>
    Baby Let's ride Hey<br>
    빨리 나와 Skkkkkrt<br>
    어서 타 달리자 어디든 괜찮아<br>
    Baby Let's ride<br>
    Let's do it All night<br>
    다 태워 먼저 부모님 또<br>
    뒷바라지해준 여자친구<br>
    절대 아냐 허세나 생색<br>
    내 차엔 없거든 Airback<br>
    돈 번 다는 말은 진짜<br>
    종이 쪼가리 몇 장을<br>
    바라는 게 아냐<br>
    알아서 따라올 걸 알아<br>
    이젠 사치가 된 부모님의 걱정<br>
    한낱 소원 같은 게 아니었어<br>
    I love my car my ride<br>
    네 바퀴 달린 왕좌<br>
    U know U want it baby<br>
    Shotgun it baby<br>
    Strap on your seatbelt<br>
    Let's ride<br>
    I love my car my ride<br>
    네 바퀴 달린 천사<br>
    Zero to one hunnit baby<br>
    We runnin crazy<br>
    Let's make some noise<br>
    오빠 차 뽑았다 널 데리러 가<br>
    Baby Let's ride Hey<br>
    빨리 나와 Skkkkkrt<br>
    어서 타 달리자 어디든 괜찮아<br>
    Baby Let's ride Hey<br>
    Let's do it All night<br>
    운전면허 딴 적은 없어도<br>
    아끼고 안 쓰고 벌어<br>
    그 당시 전 재산 털어<br>
    십년은 넘은<br>
    아빠차를 바꿔드렸어 <br>
    한 달 뒤에 주차장에 세워져 <br>
    먼지 덮인 걸 보고 화냈지<br>
    아빠는 말했지 내 아들의 첫차<br>
    아까워서 어떻게 타겠니<br>
    For real<br>
    오빠 차 뽑았다 널 데리러 가<br>
    Baby Let's ride Hey<br>
    빨리 나와 Skkkkkrt<br>
    어서 타 달리자 어디든 괜찮아<br>
    Baby Let's ride <br>
    오빠 차 뽑았다 널 데리러 가<br>
    Baby Let's ride Hey<br>
    빨리 나와 Skkkkkrt<br>
    어서 타 달리자 어디든 괜찮아<br>
    Baby Let's ride<br>
    Let's do it All night<br>
    </h5>
</body>

app/views/home/index.html.erb
<h1>Home</h1>

app/views/home/song.html.erb
<h1>마음대로 노래를 불러주세요</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<a href="/">Home</a>
<a href="/about">About</a>
<a href="/song">Sing a song~</a>
<a href="/contacts">연락처</a>
<%= yield %>

</body>
</html>